### ISSUE TITLE
(SUGGESTION) Lethal Hands digging 

### ISSUE THREAD

**Issue by VanilaBOI** [XuuXiao/CodeRebirth#10]
I really like how you encourage gathering shovels and keys to get loot from crates.

Sadly with lethal hands installed you can just by pass all of that which is the opposite I want with my Vanilla+ Modpack.

Would it be possible to disable this or make a config for the people who like it that way?

**Comment by XuuXiao** [comment]
sure ill make it a config that it's shovel only by default

**Comment by XuuXiao** [comment]
donezo, i think, will be shown if it works next version

**Comment by VanilaBOI** [comment]
Wow that was fast
Thanks a lot, your the best🥰
