### ISSUE TITLE
[Suggestion & idea] Hoverboard item (and maybe battery for it?)

### ISSUE THREAD

**Issue by TheComicRelief** [XuuXiao/CodeRebirth#7]
I want the hoverboard to have an option to take up a item slot kinda like the wallet does. It would weigh 24~ lbs when held but 0 lbs when mounted. You can lmb to switch mode and maybe it can have a battery life.

**Comment by XuuXiao** [comment]
I can do the weighing down, and the battery life but i'm not too sure about the slots part, with how complicated the hoverboard is it might get weird

**Comment by TheComicRelief** [comment]
OK thank you. BTW can you make wooden crates and metal crates abundance separated?

**Comment by XuuXiao** [comment]
I'll try

**Comment by XuuXiao** [comment]
update: a bit late but did that lol in my dev release

**Comment by TheComicRelief** [comment]
I see that you added the weight and battery to the hoverboard but what about the crates?

**Comment by XuuXiao** [comment]
There should be weights? Let me check, I mightve separated the logic but not config'd it

**Comment by XuuXiao** [comment]
Yeah in crate options

**Comment by TheComicRelief** [comment]
I am so goddamn stupid and i am very sorry ;( i see it now.
