### ISSUE TITLE
[BUG]: Tornado getting Stuck

### ISSUE THREAD

**Issue by VanilaBOI** [XuuXiao/CodeRebirth#8]
### Installation Method

r2modman / r2mm

### What happened?

I have only tested it on Experimentation but the Tornado is always to the right of the ship and doesn't move.
+ Which is the annoying part: When you are back in orbit you can still hear it and when you land on any moon, the tornado is still there to the right of the landing zone of the ship.

### What did you do?

1. Went on Experimentation while it was windy
2. Took of
3. Landed on march while it was clear

V62

### Version

v49

### What OS are you running?

Windows 10

### List of mods used

Just CodeRebirth

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XuuXiao** [comment]
if you wouldnt mind, disabling the tornado on config for now, fixed in the dev version i havent released yet.

**Comment by VanilaBOI** [comment]
Glad to hear it, will do
Thanks a lot for the lighting quick fix
