### ISSUE TITLE
[BUG]: Snow Globe Animation

### ISSUE THREAD

**Issue by VanilaBOI** [XuuXiao/CodeRebirth#9]
### Installation Method

r2modman / r2mm

### What happened?

After holding the snow globe, the holding animation for mot items are the same as the one for the snow globe.

### What did you do?

1. Picked up a snow globe
2. picked up an engine

### Version

v49

### What OS are you running?

Windows 10

### List of mods used

- ImmersiveScrap
- advanced company
- too many emotes
I don't know if it is one of them, I just had them at the time

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XuuXiao** [comment]
very odd, not entirely sure if it's on my mod's end but i have changed the animation for the next version already
